### ISSUE TITLE
탭과 스페이스 중 하나로 통일해주세요

### ISSUE THREAD

**Issue by clucle** [YouMustStudy/ChatServer#1]
소켓쪽 기본 코드를 복사해오면서 발생한 것 같습니다.

https://github.com/YouMustStudy/ChatServer/blob/557c38afcc92f7aa8d6caeef09bfdcb7a381f4bd/ChatServer/CHATSERVER.cpp#L70-L86

**Comment by YouMustStudy** [comment]
문제 확인하였으며
인덴트를 탭(Ctrl + K + F)로 통일했습니다.
