### ISSUE TITLE
유저 SendChat에서 socket이 없을 때 로그가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by clucle** [YouMustStudy/ChatServer#3]
return; 만 해서 문제 상황을 인식하지 못할 위험이 있습니다.

https://github.com/YouMustStudy/ChatServer/blob/ca617d5380e78781f9cc3cf23621def1f6f0fc1d/ChatServer/User.cpp#L4-L11

**Comment by YouMustStudy** [comment]
서버 콘솔 상에서 로그를 남기도록 수정하였습니다.
