### ISSUE TITLE
룸매니저를 사용하는 의도로 보았을 때, 싱글톤 패턴이 적합해 보입니다.

### ISSUE THREAD

**Issue by clucle** [YouMustStudy/ChatServer#4]
ChatServer에서 member 변수로 사용하면서 Initialize 하고 Room class의 static 변수에 포인터를 지정하는 것으로 보입니다.

모든 room 에서 동일하게 사용하고, chatserver에서도 보유하고 있으므로 싱글톤 패턴을 쓰는 것이 코드가 더 보기 편해질 것 같습니다.

https://github.com/YouMustStudy/ChatServer/blob/ca617d5380e78781f9cc3cf23621def1f6f0fc1d/ChatServer/CHATSERVER.h#L41-L43

https://github.com/YouMustStudy/ChatServer/blob/ca617d5380e78781f9cc3cf23621def1f6f0fc1d/ChatServer/Room.cpp#L98-L102

**Comment by YouMustStudy** [comment]
보신 것이 맞습니다.
싱글톤 패턴으로 교체하였습니다.
